travis:
  secure:
    BINSTAR_TOKEN: OQHxRcKnD4T8UN9WbliTkr9l9+98Uj3Ld9IZDjLzx8kB8WzTQ68XBrHFRj0FX2d8CoRSz9T5JNL+tdKxI301iT0yOZBpTvmlJ6qG3Cef72I2YO8TuNoLjC34VnS2v+OkG2A1PQ9iVFjRltcILruFHxBbUou/K8P6fMXgZpymV/Q5cKjmOguJvYop9uQMKQJOk+13V2HKhtafKUoTcEqR5+EWUrbqiMYq0tmfGQmAdJjaltt+/87t5RW8CBa9ICYM9KC3BoyzsorhESqGCmREwyDDkzhxYC2m3RsFii/HIu/2aU3Qzpjnrahl07ad4pWa1D/M0BhmDxV4qhPVoa+3tpgJZ4FEdSPB/0x/d2RaBrbvdzPZHKSXqCZ8R4y/aGkpAlR71wcjy4NDmqlmvZTdS3xlqLkZRoHzGNsVfAKmBss7iPa2ARgs9EuLClNYnuIrDhcTSa/Dn+utrqQaShnfRNw7cA3KYWSDK4KkhLZ10ksV0rZzEPKXoN/C7VPX3uY7dYfuJvRK1B0xcVutEZnzcy6lMF3Xr4alae6FLS6JW17LKyboNLcWi8NU18SAG2iFvdUoGGtS9WeulHOgsiugvPCL1jG972hA3qG+hCw2vFX+KNfW8UUOC+ekpW3YYjmH8n8Dp7ScC35z92lKfCm8aMxDYaXJFdPrZpSczcQyoYg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
